import type {Metadata} from 'next';
import {PropsWithChildren} from 'react';
import StyledJsxRegistry from './registry';
import 'assets/styles/reset.scss';

export const metadata: Metadata = {
  title: 'Random Draw',
  description: 'Generated by create next app',
  themeColor: '#eee',
  icons: '/favicon.ico'
};

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="ko">
      <body className="root-body">
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
