import type {Metadata} from 'next';
import {PropsWithChildren} from 'react';
import StyledJsxRegistry from 'app/registry';
import 'assets/styles/reset.scss';

export const metadata: Metadata = {
  title: 'Random Draw',
  description: 'Generated by create next app',
  themeColor: 'red',
  icons: 'app/favicon.ico'
};

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="ko">
      <body>
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
