import type {Metadata} from 'next';
import 'assets/styles/reset.scss';
import {PropsWithChildren} from 'react';
import StyledJsxRegistry from 'app/registry';
import Spinner from 'components/spinner/Spinner';
import AlertModal from 'components/modal/AlertModal';
import RecoilProvider from 'data/RecoilProvider/RecoilProvider';

export const metadata: Metadata = {
  title: 'Random Draw',
  description: 'Generated by create next app',
  themeColor: 'red',
  icons: 'app/favicon.ico'
};

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="ko">
      <RecoilProvider>
        <body suppressHydrationWarning={true}>
          <Spinner />
          <StyledJsxRegistry>{children}</StyledJsxRegistry>
          <AlertModal />
        </body>
      </RecoilProvider>
    </html>
  );
}
